# Modified from LevelDB's GitHub workflows file.
name: CI
on: [pull_request, push]
permissions:
  contents: read
jobs:
  build-and-test:
    name:  >-
      CI
      ${{ matrix.os }}
      ${{ matrix.compiler }}
      ${{ matrix.optimized && 'release' || 'debug' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [clang, gcc]
        os: [ubuntu-latest, macos-latest]
        optimized: [true, false]
        include:
          - compiler: clang
            CC: clang
            CXX: clang++
          - compiler: gcc
            CC: gcc
            CXX: g++
    env:
      CMAKE_BUILD_DIR: ${{ github.workspace }}/build
      CMAKE_BUILD_TYPE: Debug
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}
      BINARY_PATH: ${{ format('{0}/build/', github.workspace) }}
    steps:
      - uses: actions/checkout@v2
      - name: Generate Build Configuration
        run: cmake -S "${{ github.workspace }}" -B "${{ env.CMAKE_BUILD_DIR }}" -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }}
      - name: Build
        run: cmake --build "${{ env.CMAKE_BUILD_DIR }}" --config "${{ env.CMAKE_BUILD_TYPE }}"
      - name: Run Tests
        working-directory: ${{ github.workspace }}/build
        run: ctest -C "${{ env.CMAKE_BUILD_TYPE }}" --verbose