# Modified from LevelDB's GitHub workflows file.
name: CI
on: [pull_request, push]
permissions:
  contents: read
jobs:
  build-and-test:
    name: Build & Test (${{ matrix.compiler }} on ${{ matrix.os }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [clang, gcc]
        os: [ubuntu-latest, macos-latest]
        optimized: [true]
        include:
          - compiler: clang
            CC: clang
            CXX: clang++
          - compiler: gcc
            CC: gcc
            CXX: g++
    env:
      CMAKE_BUILD_DIR: ${{ github.workspace }}/build
      CMAKE_BUILD_TYPE: RelWithAssertions
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}
      BINARY_PATH: ${{ github.workspace }}/build
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: >-
          cmake -S "${{ github.workspace }}" -B "${{ env.CMAKE_BUILD_DIR }}" 
          -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }}
          -DCMAKE_LDFLAGS=-fsanitize=address,thread,undefined
          -DCALICO_BUILD_EXAMPLES=On
          -DCALICO_USE_VALIDATORS=On
          -DCALICO_BUILD_TESTS=On
      - name: Build
        run: >-
          cmake --build "${{ env.CMAKE_BUILD_DIR }}" 
          --config "${{ env.CMAKE_BUILD_TYPE }}"
      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest -V -C "${{ env.CMAKE_BUILD_TYPE }}"