# Modified from LevelDB's GitHub workflows storage.
name: CI

on: [pull_request, push]

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build & Test (${{ matrix.compiler }} on ${{ matrix.os }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [clang, gcc]
        os: [ubuntu-latest, macos-latest]
        build_type: [Debug, Release]
        include:
          - compiler: clang
            os: ubuntu-latest
            build_type: Release
            fuzz: -DCALICODB_BuildFuzzers=On -DCALICODB_FuzzerStandalone=On

    env:
      CMAKE_BUILD_DIR: ${{ github.workspace }}/build
      CMAKE_BUILD_TYPE: ${{ matrix.build_type }}
      CXX: ${{ matrix.compiler }}
      BINARY_PATH: ${{ github.workspace }}/build

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: >-
          cmake -S ${{ github.workspace }} -B ${{ env.CMAKE_BUILD_DIR }}
                -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} ${{ matrix.fuzz }}
                -DCMAKE_CXXFLAGS='-fsanitize=address,undefined'

      - name: Build
        run: >-
          cmake --build "${{ env.CMAKE_BUILD_DIR }}" 
                --config "${{ env.CMAKE_BUILD_TYPE }}"

      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest -V -C "${{ env.CMAKE_BUILD_TYPE }}"