# Modified from LevelDB's GitHub workflows storage.
name: CI

on: [pull_request, push]

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build & Test (${{ matrix.build_type }}, ${{ matrix.compiler }} on ${{ matrix.os }}))
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        compiler: [clang, gcc]
        os: [ubuntu-latest, macos-latest]
        build_type: [Debug, Release]
        include:
          # Compiler environment variables for each build type.
          - compiler: clang
            CC: clang
            CXX: clang++
          - compiler: gcc
            CC: gcc
            CXX: g++

    env:
      BUILD_DIR: "${{ github.workspace }}/build"
      BUILD_TYPE: ${{ matrix.build_type }}
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        run: >-
          cmake -S "${{ github.workspace }}" -B "${{ env.BUILD_DIR }}"
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCALICODB_CI=On
          -DCALICODB_BuildFuzzers=On -DCALICODB_FuzzerStandalone=On

      - name: Build
        run: >-
          cmake --build "${{ env.BUILD_DIR }}" 
          --config ${{ env.BUILD_TYPE }}

      - name: Test
        working-directory: "${{ env.BUILD_DIR }}"
        run: ctest -V -C ${{ env.BUILD_TYPE }}